Repository institute-atri/deep, pull requests merged in 2024-05, with the labels that each got.

#17 feat(ci): sonarcloud implementation for security improvement (#15)
  .github/workflows/sonarcloud.yml
  pom.xml
Labels: enhancement

#30 fix: application profile, relationship occurrence defendants
  src/main/java/org/instituteatri/deep/model/Defendant.java
  src/main/java/org/instituteatri/deep/model/Occurrence.java
  src/main/resources/application-test.yml
Labels: bug

#33 fix: sonar cloud pipeline does not execute #31
  .github/workflows/sonarcloud.yml
Labels: bug

#49 feat: remove docker-compose.yml file in project
  docker-compose.yml
Labels: update

#53 refactor the UserController and AuthenticationController tests
  src/main/java/org/instituteatri/deep/controller/UserController.java
  src/main/java/org/instituteatri/deep/dto/request/UpdateUserRequestDTO.java
  src/main/java/org/instituteatri/deep/exception/user/UserNotFoundException.java
  src/main/java/org/instituteatri/deep/service/UserService.java
  src/test/java/org/instituteatri/deep/controller/AuthenticationControllerTest.java
  src/test/java/org/instituteatri/deep/controller/UserControllerTest.java
  src/test/java/org/instituteatri/deep/service/UserServiceTest.java
Labels: enhancement
